name: Build and Release Extension

on:
  push:
    tags:
      - 'v*' # Triggers on tag push matching v*, like v1.0.0
  workflow_dispatch: # Allows manual trigger from GitHub UI

# Add permissions needed for creating releases
permissions:
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/tags/')

      - name: Create build directory
        run: mkdir -p build

      - name: Install dependencies
        run: pnpm install

      - name: Update version in manifest files
        if: startsWith(github.ref, 'refs/tags/')
        run: pnpm update-version ${{ env.VERSION }}

      - name: Build Chrome extension
        run: pnpm build:chrome

      - name: Build Firefox extension
        run: pnpm build:firefox

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            build/arena-clipper-chrome.zip
            build/arena-clipper-firefox.zip 